name: Build iOS Cheat
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Install iOS Workload
        run: dotnet workload install ios
      - name: Build
        run: dotnet build VanguardBrawl.csproj -c Release -f net8.0-ios -r ios-arm64 /p:BuildIpa=false /p:CheckEolTargetFramework=false
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: MyCheat
          path: bin/Release/net8.0-ios/ios-arm64/*.dll
