name: Build iOS Cheat
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Force SDK Version
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # Forza l'uso della 8, ignorando la 10

      - name: Install Workload
        run: dotnet workload install ios --ignore-failed-sources

      - name: Build Final
        run: |
          dotnet build VanguardBrawl.csproj -c Release -f net8.0-ios -r ios-arm64 \
          /p:CheckEolTargetFramework=false \
          /p:BuildIpa=false
        
      - name: Export
        uses: actions/upload-artifact@v4
        with:
          name: MyCheat
          path: bin/Release/net8.0-ios/ios-arm64/*.dll
